### ISSUE TITLE
Duktape enable Debug FLAG

### ISSUE THREAD

**Issue by agustindev** [cashapp/quickjs-java#178]
Hi, I have some interfaces of JSRuntime and are currently implemented with ducktape-android java wrapper. Everything works great with ducktape native engine. 

But the problem is when I try to connect Duktape Debugger plugin from VisualStudio Code, everything seems to be configured well, so I invest in the native code of Duktape, specially in debugger section, the "custom debugger protocol" which is compatible thanks of the VSCode Debugger Adapter implemented inside the Duktape Extension.
https://github.com/svaarala/duktape/tree/master/debugger
https://marketplace.visualstudio.com/items?itemName=HaroldBrenes.duk-debug
https://github.com/harold-b/vscode-duktape-debug
https://github.com/harold-b/vscode-duktape-debug/blob/master/src/DukDebugger.ts
https://code.visualstudio.com/api/extension-guides/debugger-extension

            "name"        : "Duk Attach",
            "type"        : "duk",
            "request"     : "attach",
            "stopOnEntry" : false,
            "address"     : "localhost",
            "port"        : 9091,

Dont know if debug flags are active in duktape-android wrapper implementation
https://github.com/svaarala/duktape/blob/master/doc/debugger.rst

```

// Required to enable debugger support:
#define DUK_USE_DEBUGGER_SUPPORT
#define DUK_USE_INTERRUPT_COUNTER

// To enable heap object inspection:
// Note: If this option is not enabled, you will only
//  be able to inspect local variables in the call stack.
//  No object properties will be inspectble.
#define DUK_USE_DEBUGGER_INSPECT

// (Optional) To forward log calls to the client:
#define DUK_USE_DEBUGGER_FWD_LOGGING
#define DUK_USE_DEBUGGER_FWD_PRINTALERT

// (Optional) To notify the client when an error is about to be thrown:
#define DUK_USE_DEBUGGER_THROW_NOTIFY

// (Optional) To pause on an uncaught errors:
#define DUK_USE_DEBUGGER_PAUSE_UNCAUGHT

// The following option to enable the 'DumpHeap' command is currently unsupported.
#define DUK_USE_DEBUGGER_DUMPHEAP
```

**Comment by JakeWharton** [comment]
We are switching to the QuickJS engine and I don't thin it has an equivalent, sorry.
