### ISSUE TITLE
Question: How to change DUK_USE_CALLSTACK_LIMIT 

### ISSUE THREAD

**Issue by jimmykane** [cashapp/quickjs-java#179]
Hi there, 

with the latest release is there a way to change the DUK_USE_CALLSTACK_LIMIT to something bigger

**Comment by JakeWharton** [comment]
No, we ship a compiled version of Duktape's sources with all configuration set in stone. What problems are you having?

**Comment by JakeWharton** [comment]
I have published Duktape-Android 1.4.0 which bundles Duktape 2.6.0. This will be the final release of a Duktape repackaging as we are switching to QuickJS.
